### ISSUE TITLE
Add a create-react-app v2.0 based starter

### ISSUE THREAD

**Issue by mehiel** [sw-yx/fresh-async-react#7]
@sw-yx if you're interested in a CRA v2.0 based starter for this list I created one at https://github.com/mehiel/cra-suspense-starter

Using it on a recent project [1] and the intention is to keep this up to date as the React team finalizes the APIs and release v17. Of course as we approach v17 those starters should fade out but till then they may come in handy.

[1] relevant twitter thread: https://twitter.com/mehieltwit/status/1041385026959695872

**Comment by sw-yx** [comment]
ooo. thanks!

**Comment by mehiel** [comment]
One day out of office and I missed the release :) 
Things change faster that expected as we approach React Conf! Which is a "yay".

So, I did the [update](https://github.com/mehiel/cra-suspense-starter/commit/bc4f8b268b9e1719ae3228e04b1e34c9bfa07c23) on the starter to actually remove all local modules. But I'm not sure that a starter is now required, since we have a release!

I'll make the PR though.

**Comment by sw-yx** [comment]
appreciate the contribution!

**Comment by sw-yx** [comment]
fyi @mehiel simple cache provider is now react-cache

**Comment by mehiel** [comment]
@sw-yx I know. If you see the [commit message](https://github.com/mehiel/cra-suspense-starter/commit/f273a6668a091fa5984694fddfdcac7d60a3c10a) I changed it back to simple-cache-provider because it's not yet on npm [1]. Is it?

In any case till now the API is the same between the two. Afaik, It's [facebook/react#13337](https://github.com/facebook/react/pull/13337) that is going to change things. Feel free to correct me if I'm wrong.

[1] https://www.npmjs.com/package/react-cache

**Comment by sw-yx** [comment]
its available as react-cache@canary :)
